version: '3.9'

services:
  oracledb:
    image: gvenzl/oracle-xe:21.3.0
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: password
      APP_USER: test_user
      APP_USER_PASSWORD: test_password

  test:
    build: .
    environment:
      NODE_ENV: test
    volumes:
      - ./:/opt/marv-oracle-db-driver
    depends_on:
      - oracledb
